---
abstract: 'Pure Perl implementation for parsing/writing XML documents'
author:
  - kawanet
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-TreePP
no_index:
  directory:
    - t
    - inc
requires:
  LWP: 5.811
  Test::More: 0
version: 0.42
